# -*- coding: utf-8 -*-
"""pyspark_job.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGq2CdKGdRjB3z8f70yqOmhjq9infOjq
"""

from pyspark.sql import DataFrame
from pyspark.sql.functions import col


def clean_data(df: DataFrame) -> DataFrame:
    """
    Cleans the input DataFrame by:
    - Removing rows where amount <= 0
    - Removing rows where name is NULL
    - Adding 'amount_with_tax' column (amount * 1.20)
    """
    return (
        df.filter(col("amount") > 0)
        .filter(col("name").isNotNull())
        .withColumn("amount_with_tax", col("amount") * 1.20)
    )