# -*- coding: utf-8 -*-
"""test_pyspark_job

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WGq2CdKGdRjB3z8f70yqOmhjq9infOjq
"""

import pytest
from pyspark.sql import SparkSession
from pyspark.sql.types import DoubleType, StringType, StructField, StructType
from pyspark_job import clean_data


@pytest.fixture(scope="session")
def spark():
    """Shared SparkSession fixture for PyTest."""
    return (
        SparkSession.builder.master("local[1]")
        .appName("pyspark-unit-tests")
        .getOrCreate()
    )


def test_clean_data(spark):
    schema = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("amount", DoubleType(), True),
        ]
    )

    # Input data covering edge cases (amount <= 0, NULL name, valid rows)
    data = [
        ("1", "Alice", 100.0),  # Valid row
        ("2", "Bob", 0.0),  # Filtered out: amount <= 0
        ("3", "Charlie", -50.0),  # Filtered out: amount < 0
        ("4", None, 200.0),  # Filtered out: name is NULL
    ]

    input_df = spark.createDataFrame(data, schema)
    result_df = clean_data(input_df)

    results = result_df.collect()

    # 1. Verify valid records are kept and invalid records removed
    assert len(results) == 1

    # 2. Verify row content and amount_with_tax calculation
    row = results[0]
    assert row["id"] == "1"
    assert row["name"] == "Alice"
    assert row["amount"] == 100.0
    assert row["amount_with_tax"] == pytest.approx(120.0, rel=1e-3)